In [ ]:
import pickle

In [ ]:
# Load the saved model using pickle
with open("/content/transaction_pickle", 'rb') as file:
    model = pickle.load(file)

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_excel("/content/data_version_excel_v2.xlsx")
data.head()

,Unnamed: 0,Date,Id_compte,amount_transaction,category_transaction,Description,Type_transaction
0,0,2022-01-01 16:01:00,SEW0C_LI.1,3.39,Food & Drink - Coffee and tea,Latte purchase,Debit
1,1,2022-01-01 19:46:00,SEW0C_LI.1,3.39,Bank Transfers - ATM withdrawals,ATM withdrawal - $,Debit
2,2,2022-01-01 06:47:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Bus fare payment,Debit
3,3,2022-01-01 19:22:00,SEW0C_LI.1,1.70,Transportation - Public Transport,Train ticket purchase,Debit
4,4,2022-01-01 05:49:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Subway ride cost,Debit

In [ ]:
# Set the max_rows option to display all categories
pd.set_option('display.max_rows', None)

# Calculate the frequency counts
categories = data['category_transaction'].unique()



# Print the frequency counts
print(categories)

['Food & Drink - Coffee and tea' 'Bank Transfers - ATM withdrawals'
 'Transportation - Public Transport' 'Bank Transfers - ATM fees'
 'Food & Drink - Vending machines' 'Transportation - Parking'
 'Bank Transfers - Other bank fees' 'Supermarkets - Groceries'
 'Medical - Pharmacies and supplements' 'Food & Drink - Groceries'
 'General Services - Home Repair + Maintenance'
 'General Merchandise - Houseware' 'Transportation-Taxis and rideshares'
 'Transportation - Gas' 'Transportation - Tolls'
 'Food & Drink - Restaurants' 'General Merchandise - Clothing'
 'Food & Drink - Fast food' 'Bank Transfers - Overdraft fees'
 'Bank Transfers - Foreign transaction fees' 'General Merchandise - Books'
 'Entertainment - Amusement Parks' 'Medical - Veterinary services'
 'Food & Drink - Food delivery' 'Food & Drink - Alcohol & Bars'
 'General Merchandise - Pet supplies' 'Entertainment - Video games'
 'Entertainment - TV and movies' 'Entertainment - Other'
 'General Merchandise - Sporting goods'
 'General Services - Health + Fitness' 'Income - Salary'
 'Subscription - Others' 'Rent & Utilities - Water'
 'Rent & Utilities - Rent' 'Rent & Utilities - Mobile Phone'
 'Loans - Credit card payment' 'Travel - Flights' 'Credit card payment'
 'Rent & Utilities - Internet' 'Entertainment  - TV and movies'
 'Travel - Lodging' 'General Merchandise - Electronics'
 'Income - Tax refund' 'General Merchandise  - Other'
 'Entertainment  - Casinos and gambling' 'Travel  - Rental cars'
 'Transportation - Automobile maintenance and fees'
 'Loans - Car loan payments'
 'General Services - Other non entertainment online subscriptions'
 'General Services  - Education' 'General Services  - Cloud storage'
 'Income - Other' 'General Services - Other Insurance'
 'General Merchandise - Online Marketplaces' 'General Merchandise - Other'
 'General Services - Shipping + Postage'
 'General Merchandise - Product refunds'
 'General Services - Service refunds' 'Loans - Mortgage payments'
 'Loans - Personal loans' 'General Services - Health insurance'
 'Government + Non-Profit - Taxes' 'Bank Transfers - Banking rewards'
 'General Services - Auto insurance' 'Government + Non-Profit - Other'
 'Government + Non-Profit - Other donations'
 'Government + Non-Profit - Political donations']

In [ ]:
data['category_transaction'].value_counts()

Bank Transfers - ATM fees                                          4376
Transportation - Public Transport                                  3611
Transportation - Parking                                           2778
Bank Transfers - ATM withdrawals                                   2556
Food & Drink - Coffee and tea                                      2540
Food & Drink - Vending machines                                    1471
Bank Transfers - Other bank fees                                   1079
Medical - Pharmacies and supplements                                694
Transportation-Taxis and rideshares                                 507
Food & Drink - Groceries                                            384
Transportation - Tolls                                              375
Transportation - Gas                                                356
General Services - Home Repair + Maintenance                        267
Bank Transfers - Overdraft fees                                     216
Supermarkets - Groceries                                            200
Food & Drink - Restaurants                                          198
General Merchandise - Houseware                                     146
Entertainment - Amusement Parks                                     145
Income - Salary                                                     144
Food & Drink - Fast food                                            140
Subscription - Others                                               133
General Merchandise - Clothing                                      128
General Merchandise - Books                                         110
Rent & Utilities - Mobile Phone                                      98
Rent & Utilities - Internet                                          97
Rent & Utilities - Water                                             87
Rent & Utilities - Rent                                              84
Food & Drink - Alcohol & Bars                                        82
Entertainment - TV and movies                                        68
Food & Drink - Food delivery                                         67
General Services - Other non entertainment online subscriptions      64
Entertainment - Video games                                          61
General Merchandise - Sporting goods                                 52
General Merchandise - Pet supplies                                   52
General Services - Health + Fitness                                  47
Medical - Veterinary services                                        44
Transportation - Automobile maintenance and fees                     43
General Services - Other Insurance                                   40
Loans - Credit card payment                                          35
Income - Other                                                       34
Travel - Lodging                                                     28
Bank Transfers - Foreign transaction fees                            26
General Merchandise  - Other                                         26
Entertainment - Other                                                25
General Merchandise - Electronics                                    25
Travel - Flights                                                     23
Entertainment  - TV and movies                                       21
Entertainment  - Casinos and gambling                                14
General Services  - Cloud storage                                    13
Loans - Mortgage payments                                            12
General Merchandise - Online Marketplaces                            11
General Services  - Education                                        11
General Merchandise - Other                                          10
Loans - Personal loans                                               10
General Services - Health insurance                                   9
Government + Non-Profit - Taxes                                       9
Income - Tax refund                                                   9
Loans - Car loan payments                                             9
Credit card payment                                                   8
General Services - Shipping + Postage                                 7
Travel  - Rental cars                                                 6
General Services - Auto insurance                                     4
Government + Non-Profit - Other                                       4
General Merchandise - Product refunds                                 4
General Services - Service refunds                                    3
Government + Non-Profit - Other donations                             3
Bank Transfers - Banking rewards                                      2
Government + Non-Profit - Political donations                         2
Name: category_transaction, dtype: int64

In [ ]:
IDs = data['Id_compte'].unique()



# Print the frequency counts
print(IDs)

['SEW0C_LI.1' 'SEW0C_HI.1' 'SEWC_CL.1' 'US.1' 'IPA.1' 'SEWC_P.1'
 'SEWC_PA.1' 'TA.1' 'HP.1' 'CPA.1' 'CPA_MP.1' 'SEWC_P_PL.1']

In [ ]:
datagpt=pd.read_excel("/content/mockdata.xlsx")
datagpt.head()

,Account ID,Transaction Amount,Transaction Description,Transaction Category
0,SEW0C_LI.1,20.50,Starbucks - Grande Cappuccino,Food & Drink - Coffee and tea
1,SEW0C_LI.1,15.75,Freshmart - Organic Vegetables,Supermarkets - Groceries
2,SEW0C_LI.1,50.00,Trendy Threads - Summer Dress,General Merchandise - Clothing
3,SEW0C_LI.1,8.99,City Cab - Ride to Airport,Transportation - Taxis and rideshares
4,SEW0C_LI.1,12.00,"Bookworm's Paradise - ""The Alchemist""",General Merchandise - Books

In [ ]:
double=datagpt[datagpt.duplicated()]
double

,Account ID,Transaction Amount,Transaction Description,Transaction Category
175,HP.1,10.00,GlobalBank - Other Bank Fee,Bank Transfers - Other bank fees
217,SEW0C_HI.1,6.25,Morning Brew - Medium Iced Coffee,Food & Drink - Coffee and tea
218,SEW0C_HI.1,12.50,Pizza Palace - Family Pizza Combo,Food & Drink - Restaurants
219,SEW0C_HI.1,38.00,Gas Stop - Fuel,Transportation - Gas
220,SEW0C_HI.1,16.99,Home Essentials - Cleaning Supplies,General Merchandise - Houseware
...,...,...,...,...
2938,SEW0C_LI.1,215.00,Professional House Cleaning Service,General Services - Other non-entertainment
2939,SEW0C_HI.1,185.00,Garden Landscaping and Maintenance,General Services - Other non-entertainment
2940,SEWC_CL.1,145.00,Personal Fitness Training Sessions,General Services - Other non-entertainment
2941,US.1,310.00,Legal Consultation and Advisory Services,General Services - Other non-entertainment
2942,IPA.1,105.00,Computer Repair and Troubleshooting,General Services - Other non-entertainment

In [ ]:
datagpt.drop_duplicates(inplace=True)
double=datagpt[datagpt.duplicated()]
double

Empty DataFrame
Columns: [Account ID, Transaction Amount, Transaction Description, Transaction Category]
Index: []

In [ ]:
datagpt.shape

(2136, 4)

In [ ]:
datagpt['Transaction Category'].value_counts()

Bank Transfers - Overdraft fees              81
General Services - Education                 69
Travel - Rental cars                         62
Entertainment - TV and movies                62
Credit card payment                          62
                                             ..
Transportation - Public Transport             6
Bank Transfers - Other bank fees              5
Travel - Lodging                              3
General Merchandise - Online Marketplaces     3
Medical - Veterin ary services                2
Name: Transaction Category, Length: 68, dtype: int64

In [ ]:
# Perform one-hot encoding for the "account_id" feature
encoded_data = pd.get_dummies(datagpt, columns=['Account ID'], prefix='account')
# Print the encoded data
print(encoded_data.head())

   Transaction Amount                Transaction Description  \
0               20.50          Starbucks - Grande Cappuccino
1               15.75         Freshmart - Organic Vegetables
2               50.00          Trendy Threads - Summer Dress
3                8.99             City Cab - Ride to Airport
4               12.00  Bookworm's Paradise - "The Alchemist"

                    Transaction Category  account_CPA.1  account_CPA_MP.1  \
0          Food & Drink - Coffee and tea              0                 0
1               Supermarkets - Groceries              0                 0
2         General Merchandise - Clothing              0                 0
3  Transportation - Taxis and rideshares              0                 0
4            General Merchandise - Books              0                 0

   account_HP.1  account_IPA.1  account_SEW0C_HI.1  account_SEW0C_LI.1  \
0             0              0                   0                   1
1             0              0                   0                   1
2             0              0                   0                   1
3             0              0                   0                   1
4             0              0                   0                   1

   account_SEWC_CL.1  account_SEWC_P.1  account_SEWC_PA.1  \
0                  0                 0                  0
1                  0                 0                  0
2                  0                 0                  0
3                  0                 0                  0
4                  0                 0                  0

   account_SEWC_P_PL.1  account_TA.1  account_US.1
0                    0             0             0
1                    0             0             0
2                    0             0             0
3                    0             0             0
4                    0             0             0

In [ ]:
one_hot_ID=encoded_data.drop(['Transaction Amount','Transaction Category','Transaction Description'], axis =1)

In [ ]:
one_hot_array=one_hot_ID.values
one_hot_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# Extract the 'transaction amount' column
transaction_amount = datagpt['Transaction Amount']

In [ ]:
# Create an instance of the MinMaxScaler
scaler = MinMaxScaler()
# Fit and transform the transaction amount data
scaled_transaction_amount = scaler.fit_transform(transaction_amount.values.reshape(-1, 1))
# Update the 'transaction amount' column with the scaled values
datagpt['transaction_amount'] = scaled_transaction_amount
# Print the scaled 'transaction amount' column
print(datagpt['transaction_amount'])

0       0.002580
1       0.001837
2       0.007192
3       0.000780
4       0.001251
5       0.003361
6       0.030644
7       0.006410
8       0.005002
9       0.000195
10      0.000938
11      0.005629
12      0.002344
13      0.015009
14      0.000391
15      0.011882
16      0.001720
17      0.004065
18      0.000624
19      0.007192
20      0.002502
21      0.000235
22      0.001720
23      0.011882
24      0.000938
25      0.003283
26      0.002502
27      0.007192
28      0.022827
29      0.001406
30      0.000937
31      0.000625
32      0.030644
33      0.001720
34      0.003283
35      0.008755
36      0.030644
37      0.000156
38      0.000938
39      0.001875
40      0.015009
41      0.000704
42      0.000156
43      0.001720
44      0.046279
45      0.000625
46      0.002502
47      0.001251
48      0.022827
49      0.003283
50      0.000938
51      0.005629
52      0.001406
53      0.006410
54      0.022827
55      0.002502
56      0.000625
57      0.030644
58      0.001720
59      0.004065
60      0.001406
61      0.000780
62      0.002344
63      0.000938
64      0.003283
65      0.030644
66      0.007192
67      0.001720
68      0.003283
69      0.000938
70      0.000311
71      0.002344
72      0.000938
73      0.003283
74      0.030644
75      0.007192
76      0.002580
77      0.001837
78      0.007192
79      0.000780
80      0.001251
81      0.003361
82      0.030644
83      0.006410
84      0.005002
85      0.000195
86      0.000938
87      0.005629
88      0.002344
89      0.015009
90      0.000391
91      0.011882
92      0.001720
93      0.004065
94      0.000624
95      0.007192
96      0.002502
97      0.000235
98      0.001720
99      0.011882
100     0.000938
101     0.003283
102     0.022827
103     0.003283
104     0.002267
105     0.007974
106     0.000937
107     0.001718
108     0.003831
109     0.027517
110     0.005941
111     0.004533
112     0.000352
113     0.001329
114     0.005316
115     0.002031
116     0.014228
117     0.000547
118     0.012664
119     0.002189
120     0.004847
121     0.000469
122     0.007974
123     0.002971
124     0.000352
125     0.002189
126     0.011101
127     0.001251
128     0.003752
129     0.002814
130     0.007505
131     0.025954
132     0.001718
133     0.001249
134     0.000547
135     0.035335
136     0.001954
137     0.003752
138     0.009537
139     0.038462
140     0.000078
141     0.001251
142     0.001718
143     0.018136
144     0.000547
145     0.000469
146     0.002189
147     0.054096
148     0.000391
149     0.003127
150     0.001720
151     0.027517
152     0.004847
153     0.001329
154     0.006410
155     0.000938
156     0.005629
157     0.024390
158     0.003283
159     0.000625
160     0.033771
161     0.002189
162     0.004847
163     0.001718
164     0.000624
165     0.002502
166     0.000938
167     0.003752
168     0.027517
169     0.006410
170     0.002189
171     0.003752
172     0.001718
173     0.000624
174     0.002502
176     0.003752
177     0.027517
178     0.006410
179     0.003283
180     0.002267
181     0.007974
182     0.000937
183     0.001718
184     0.003831
185     0.027517
186     0.005941
187     0.004533
188     0.000352
189     0.001329
190     0.005316
191     0.002031
192     0.014228
193     0.000547
194     0.012664
195     0.002189
196     0.004847
197     0.000469
198     0.007974
199     0.002971
200     0.000352
201     0.002189
202     0.011101
203     0.001251
204     0.003752
205     0.029862
206     0.001876
207     0.004065
208     0.001720
209     0.002502
210     0.011101
211     0.000780
212     0.001718
213     0.003831
214     0.027517
215     0.005941
216     0.004533
258     0.000625
259     0.001329
260     0.007974
261     0.000937
262     0.001718
263     0.003831
264     0.027517
265     0.005941
266     0.004533
267     0.003283
296     0.002580
297     0.001837
298     0.007192
299     0.000937
300     0.001718
301     0.003831
302     0.027517
303     0.005941
304     0.004533
305     0.000352
306     0.001329
307     0.005316
308     0.002031
309     0.014228
310     0.000547
311     0.012664
312     0.002189
313     0.004847
314     0.000469
315     0.007974
316     0.002971
317     0.000352
318     0.002189
319     0.011101
320     0.001251
321     0.003752
322     0.029862
323     0.001876
324     0.004065
325     0.001720
326     0.002502
327     0.011101
328     0.000780
329     0.001718
330     0.003831
331     0.027517
332     0.005941
333     0.004533
334     0.000352
335     0.001329
336     0.005316
337     0.002031
338     0.014228
339     0.000547
340     0.012664
341     0.002189
342     0.004847
343     0.000469
344     0.007974
345     0.002971
346     0.000352
347     0.002189
348     0.011101
349     0.001251
350     0.003752
351     0.002814
352     0.007505
353     0.025954
354     0.001718
355     0.001249
356     0.000547
357     0.035335
358     0.001954
359     0.003752
360     0.009537
361     0.038462
362     0.000078
363     0.001251
364     0.001718
365     0.018136
366     0.000547
367     0.000469
368     0.002189
369     0.054096
370     0.000391
371     0.003127
372     0.001720
373     0.027517
374     0.004847
375     0.000625
376     0.001329
377     0.007974
378     0.000937
379     0.001718
380     0.003831
381     0.027517
382     0.005941
383     0.004533
384     0.003283
385     0.000938
386     0.005629
387     0.001406
388     0.006410
389     0.022827
390     0.002502
391     0.000625
392     0.030644
393     0.001720
394     0.004065
395     0.001406
396     0.000780
397     0.002344
398     0.000938
399     0.003283
400     0.030644
401     0.007192
402     0.001720
403     0.003283
404     0.000938
405     0.000311
406     0.002344
407     0.000938
408     0.003283
409     0.030644
410     0.007192
411     0.002580
412     0.001837
413     0.007192
414     0.000937
415     0.001718
416     0.003831
417     0.027517
420     0.000352
421     0.001329
422     0.005316
423     0.002031
425     0.000547
426     0.012664
427     0.002189
428     0.004847
431     0.002971
434     0.011101
437     0.029862
457     0.004847
481     0.007974
482     0.004065
483     0.006410
484     0.007192
485     0.005629
486     0.008755
487     0.004847
488     0.007974
489     0.005629
490     0.007192
491     0.006410
492     0.004065
493     0.004847
494     0.005629
495     0.007192
496     0.007974
497     0.008755
498     0.009537
499     0.006410
500     0.007192
501     0.007974
502     0.008755
503     0.005629
504     0.006410
505     0.007192
506     0.007974
507     0.008755
508     0.006410
509     0.007192
510     0.007974
511     0.008755
512     0.004847
513     0.005629
514     0.006410
515     0.007192
516     0.005629
517     0.006410
518     0.007192
519     0.007974
520     0.008755
521     0.006410
522     0.007192
523     0.007974
524     0.008755
525     0.005629
526     0.006410
527     0.007192
528     0.007974
529     0.008755
530     0.006410
531     0.038462
532     0.022827
533     0.015009
534     0.030644
535     0.026735
536     0.018918
537     0.027517
538     0.024390
539     0.029081
540     0.033771
541     0.021263
542     0.025172
543     0.028299
544     0.032208
545     0.034553
546     0.037680
547     0.023609
548     0.026735
549     0.029862
550     0.031426
551     0.020482
552     0.024390
553     0.027517
554     0.030644
555     0.022827
556     0.025954
557     0.029081
558     0.032208
559     0.019700
560     0.025954
561     0.029862
562     0.033771
563     0.021263
564     0.024390
565     0.028299
566     0.031426
567     0.023609
568     0.026735
569     0.029862
570     0.781113
571     0.859287
572     0.937461
573     0.702939
574     0.812383
575     0.749844
576     0.734209
577     0.828018
578     0.796748
579     0.765478
580     0.874922
581     0.890557
582     0.843652
583     0.906191
584     0.812383
585     0.859287
586     0.874922
587     0.828018
588     0.890557
589     0.812383
590     0.859287
591     0.906191
592     0.843652
593     0.874922
594     0.890557
595     0.843652
596     0.906191
597     0.765478
598     0.859287
599     0.890557
600     0.812383
601     0.828018
602     0.843652
603     0.906191
604     0.874922
605     0.859287
606     0.890557
607     0.812383
608     0.906191
609     0.765478
610     0.874922
611     0.843652
612     0.890557
613     0.906191
614     0.812383
615     0.859287
616     0.874922
617     0.828018
618     0.890557
619     0.812383
620     0.906191
621     0.859287
622     0.874922
623     0.843652
624     0.890557
625     0.006410
626     0.007505
627     0.006879
628     0.007192
629     0.005941
630     0.006723
631     0.007974
632     0.007036
633     0.007661
634     0.006567
635     0.007817
636     0.007348
637     0.006879
638     0.007192
639     0.007661
640     0.006723
641     0.006410
642     0.007505
643     0.007036
644     0.006098
645     0.007192
646     0.007817
647     0.006879
648     0.007974
649     0.006567
650     0.007348
651     0.006723
652     0.007817
653     0.006879
654     0.007192
655     0.007661
656     0.006723
657     0.006410
658     0.007505
659     0.007036
660     0.006098
661     0.007192
662     0.007817
663     0.006879
664     0.007974
665     0.006567
666     0.007348
667     0.006723
668     0.007817
669     0.006879
670     0.007192
671     0.007661
672     0.006723
673     0.006410
674     0.007505
675     0.007036
676     0.233896
677     0.202627
678     0.265166
679     0.249531
680     0.218261
681     0.280801
682     0.241714
683     0.226079
684     0.257348
685     0.210444
686     0.272983
687     0.237023
688     0.244841
689     0.254221
690     0.262039
691     0.221388
692     0.246404
693     0.260475
694     0.238587
695     0.219825
696     0.263602
697     0.274547
698     0.224515
699     0.233896
700     0.241714
701     0.251094
702     0.260475
703     0.222952
704     0.247967
705     0.262039
706     0.240150
707     0.221388
708     0.265166
709     0.276110
710     0.226079
711     0.235460
712     0.243277
713     0.252658
714     0.262039
715     0.224515
716     0.249531
717     0.263602
718     0.241714
719     0.219825
720     0.263602
721     0.274547
722     0.222952
723     0.232333
724     0.240150
725     0.249531
726     0.258912
727     0.233896
728     0.249531
729     0.265166
730     0.280801
731     0.296435
732     0.312070
733     0.327705
734     0.343340
735     0.358974
736     0.374609
737     0.390244
738     0.405879
739     0.421513
740     0.437148
741     0.452783
742     0.468418
743     0.484053
744     0.499687
745     0.515322
746     0.530957
747     0.546592
748     0.562226
749     0.577861
750     0.593496
751     0.609131
752     0.624765
753     0.640400
754     0.656035
755     0.671670
756     0.687305
757     0.702939
758     0.718574
759     0.734209
760     0.749844
761     0.765478
762     0.781113
763     0.796748
764     0.812383
765     0.828018
766     0.843652
767     0.859287
768     0.874922
769     0.890557
770     0.906191
771     0.921826
772     0.937461
773     0.953096
774     0.968730
775     0.984365
776     1.000000
777     0.001798
778     0.000743
779     0.001251
780     0.002541
781     0.000937
782     0.000391
783     0.002306
784     0.001126
785     0.001642
786     0.000624
787     0.002001
788     0.000821
789     0.001485
790     0.002344
791     0.001055
792     0.000704
793     0.002072
794     0.001282
795     0.001798
796     0.000937
797     0.002001
798     0.000821
799     0.001485
800     0.002344
801     0.001055
802     0.000704
803     0.002072
804     0.001282
805     0.001798
806     0.000624
807     0.002001
808     0.000821
809     0.001485
810     0.002344
811     0.001055
812     0.000704
813     0.002072
814     0.001282
815     0.001798
817     0.002001
818     0.000821
819     0.001485
820     0.002344
821     0.001055
822     0.000704
823     0.002072
824     0.011882
825     0.006488
826     0.009537
827     0.008013
828     0.010444
829     0.005783
830     0.011179
831     0.007192
832     0.008873
833     0.005002
834     0.012695
835     0.006449
836     0.009615
837     0.010444
838     0.008013
839     0.005783
840     0.011179
841     0.007192
842     0.008873
843     0.005002
844     0.012695
845     0.006449
846     0.009615
847     0.010444
848     0.008013
850     0.011179
851     0.007192
852     0.008873
853     0.005002
854     0.012695
855     0.006449
856     0.009615
857     0.010444
858     0.008013
859     0.005783
860     0.011179
861     0.007192
864     0.012695
865     0.006449
866     0.009615
867     0.010444
868     0.008013
869     0.005783
870     0.011179
871     0.003283
872     0.005707
873     0.001720
874     0.002306
875     0.004972
876     0.002656
877     0.004143
878     0.003283
879     0.005707
880     0.001720
881     0.002306
882     0.004972
883     0.002656
884     0.004143
885     0.003283
886     0.005707
887     0.001720
890     0.002656
891     0.004143
892     0.003283
893     0.005707
894     0.001720
895     0.002306
896     0.004972
897     0.002656
899     0.003283
900     0.005707
901     0.001720
902     0.002306
903     0.004972
904     0.002656
905     0.004143
906     0.003283
909     0.002306
910     0.004972
911     0.002656
912     0.004143
913     0.003283
914     0.005707
915     0.001720
916     0.002306
920     0.003283
990     0.004847
991     0.002580
992     0.001720
993     0.007231
994     0.004190
995     0.005783
996     0.003361
997     0.002345
998     0.002932
999     0.005471
1000    0.004409
1001    0.003791
1002    0.004847
1003    0.002580
1004    0.001720
1006    0.004190
1007    0.005783
1008    0.003361
1009    0.002345
1010    0.002932
1011    0.005471
1012    0.004409
1013    0.003791
1014    0.004847
1015    0.002580
1016    0.001720
1017    0.007231
1018    0.004190
1019    0.005783
1020    0.003361
1021    0.002345
1022    0.002932
1023    0.005471
1024    0.004409
1025    0.004847
1026    0.002580
1027    0.001720
1028    0.007231
1029    0.004190
1030    0.005783
1031    0.003361
1032    0.002345
1033    0.002932
1034    0.005471
1035    0.004409
1036    0.004847
1037    0.002580
1038    0.001720
1039    0.007231
1040    0.004190
1041    0.005783
1042    0.003361
1045    0.005471
1046    0.004409
1047    0.004847
1048    0.002580
1049    0.001720
1050    0.007231
1051    0.004190
1052    0.005783
1053    0.003361
1054    0.002345
1055    0.002932
1056    0.005471
1057    0.004409
1058    0.004847
1059    0.002580
1060    0.001720
1061    0.007231
1067    0.005471
1068    0.004409
1069    0.004847
1070    0.002580
1071    0.001720
1072    0.007231
1073    0.004190
1074    0.005783
1075    0.003361
1076    0.002345
1077    0.002932
1078    0.005471
1079    0.000937
1080    0.001329
1081    0.001720
1082    0.000467
1083    0.002500
1084    0.000704
1085    0.000938
1086    0.000624
1087    0.001718
1088    0.001173
1089    0.000937
1090    0.001329
1091    0.001720
1092    0.000467
1093    0.002500
1094    0.000704
1095    0.000938
1096    0.000624
1097    0.001718
1098    0.001173
1099    0.000937
1100    0.001329
1101    0.001720
1102    0.000467
1103    0.002500
1104    0.000704
1105    0.000938
1106    0.000624
1110    0.001329
1111    0.001720
1113    0.002500
1114    0.000704
1115    0.000938
1116    0.000624
1117    0.001718
1118    0.001173
1119    0.000937
1120    0.001329
1121    0.001720
1122    0.000467
1123    0.002500
1125    0.000938
1126    0.000624
1127    0.001718
1128    0.001173
1129    0.000937
1130    0.001329
1131    0.000938
1132    0.002580
1133    0.001720
1134    0.000311
1135    0.001406
1136    0.000704
1137    0.000469
1138    0.000467
1139    0.001016
1140    0.000937
1141    0.000938
1142    0.002580
1143    0.001720
1144    0.000311
1145    0.001406
1146    0.000704
1147    0.000469
1148    0.000467
1149    0.001016
1150    0.000937
1151    0.000938
1152    0.002580
1153    0.001720
1154    0.000311
1155    0.001406
1156    0.000704
1157    0.000469
1158    0.000467
1162    0.002580
1163    0.001720
1165    0.001406
1166    0.000704
1167    0.000469
1168    0.000467
1169    0.001016
1170    0.000937
1171    0.000938
1172    0.002580
1173    0.001720
1174    0.000311
1175    0.001406
1178    0.000467
1179    0.001016
1180    0.000937
1181    0.000938
1182    0.002580
1183    0.001720
1185    0.001406
1186    0.000704
1189    0.001016
1231    0.000156
1232    0.000547
1233    0.000938
1234    0.000155
1235    0.000780
1236    0.000391
1237    0.000469
1238    0.000311
1239    0.000860
1240    0.000467
1241    0.000156
1242    0.000547
1243    0.000938
1244    0.000155
1245    0.000780
1246    0.000391
1247    0.000469
1248    0.000311
1249    0.000860
1250    0.000467
1251    0.000156
1252    0.000547
1253    0.000938
1254    0.000155
1255    0.000780
1256    0.000391
1257    0.000469
1258    0.000311
1260    0.000467
1261    0.000156
1262    0.000547
1263    0.000938
1264    0.000155
1265    0.000780
1266    0.000391
1267    0.000469
1268    0.000311
1269    0.000860
1270    0.000467
1271    0.000156
1272    0.000547
1273    0.000938
1274    0.000155
1276    0.000391
1277    0.000469
1278    0.000311
1280    0.000467
1331    0.077548
1332    0.038462
1333    0.054096
1334    0.022827
1335    0.030644
1336    0.046279
1337    0.027517
1338    0.061914
1339    0.042370
1340    0.033771
1341    0.077548
1342    0.038462
1343    0.054096
1344    0.022827
1345    0.030644
1346    0.046279
1347    0.027517
1348    0.061914
1349    0.042370
1350    0.033771
1351    0.077548
1352    0.038462
1353    0.054096
1354    0.022827
1355    0.030644
1356    0.046279
1357    0.027517
1358    0.061914
1362    0.038462
1363    0.054096
1365    0.030644
1366    0.046279
1367    0.027517
1368    0.061914
1369    0.042370
1370    0.033771
1371    0.077548
1372    0.038462
1373    0.054096
1374    0.022827
1375    0.030644
1378    0.061914
1379    0.042370
1380    0.033771
1381    0.077548
1382    0.038462
1383    0.054096
1384    0.022827
1385    0.030644
1386    0.046279
1387    0.027517
1388    0.061914
1389    0.042370
1390    0.033771
1391    0.077548
1392    0.038462
1393    0.054096
1394    0.022827
1396    0.046279
1397    0.027517
1398    0.061914
1400    0.033771
1401    0.015009
1402    0.007192
1403    0.030644
1404    0.011101
1405    0.022827
1406    0.011882
1407    0.018136
1408    0.038462
1409    0.013446
1410    0.027517
1411    0.015009
1412    0.007192
1413    0.030644
1414    0.011101
1415    0.022827
1416    0.011882
1417    0.018136
1418    0.038462
1419    0.013446
1420    0.027517
1421    0.015009
1422    0.007192
1423    0.030644
1424    0.011101
1425    0.022827
1426    0.011882
1427    0.018136
1428    0.038462
1430    0.027517
1431    0.015009
1432    0.007192
1433    0.030644
1434    0.011101
1435    0.022827
1436    0.011882
1437    0.018136
1438    0.038462
1439    0.013446
1440    0.027517
1441    0.015009
1442    0.007192
1443    0.030644
1444    0.011101
1446    0.011882
1447    0.018136
1448    0.038462
1471    0.001720
1472    0.001406
1473    0.000780
1474    0.001718
1475    0.001093
1476    0.000937
1477    0.001562
1478    0.001249
1479    0.000624
1480    0.001251
1481    0.001720
1482    0.001406
1483    0.000780
1484    0.001718
1485    0.001093
1486    0.000937
1487    0.001562
1488    0.001249
1489    0.000624
1490    0.001251
1491    0.001720
1492    0.001406
1493    0.000780
1494    0.001718
1495    0.001093
1496    0.000937
1497    0.001562
1498    0.001249
1502    0.001406
1503    0.000780
1505    0.001093
1506    0.000937
1507    0.001562
1508    0.001249
1509    0.000624
1510    0.001251
1511    0.001720
1512    0.001406
1513    0.000780
1514    0.001718
1515    0.001093
1516    0.000937
1517    0.001562
1519    0.000624
1520    0.001251
1521    0.001720
1522    0.001406
1523    0.000780
1524    0.001718
1525    0.001093
1526    0.000937
1527    0.001562
1528    0.011101
1529    0.007192
1530    0.008755

In [ ]:
scaled_transaction_amount

array([[0.00257974],
       [0.00183709],
       [0.00719199],
       ...,
       [0.00953721],
       [0.01969981],
       [0.02908068]])

In [ ]:
datagpt.describe()

       Transaction Amount  transaction_amount
count         2136.000000         2136.000000
mean           395.883680            0.061270
std           1056.315803            0.165153
min              4.000000            0.000000
25%             22.000000            0.002814
50%             70.800000            0.010444
75%            290.000000            0.044715
max           6400.000000            1.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Create an instance of LabelEncoder
label_encoder = LabelEncoder()
categories=datagpt['Transaction Category'].tolist()
# Fit the encoder to the categories and transform the data
encoded_labels = label_encoder.fit_transform(categories)
# Print the encoded cat
print(encoded_labels)

[13 58 20 ... 34 34 34]

In [ ]:
label_encoder.classes_

array(['Bank Transfers - ATM fees', 'Bank Transfers - ATM withdrawals',
       'Bank Transfers - Banking rewards',
       'Bank Transfers - Foreign transaction fees',
       'Bank Transfers - Other bank fees',
       'Bank Transfers - Overdraft fees', 'Credit card payment',
       'Entertainment - Amusement Parks',
       'Entertainment - Casinos and gambling', 'Entertainment - Other',
       'Entertainment - TV and movies', 'Entertainment - Video games',
       'Food & Drink - Alcohol & Bars', 'Food & Drink - Coffee and tea',
       'Food & Drink - Fast food', 'Food & Drink - Food delivery',
       'Food & Drink - Groceries', 'Food & Drink - Restaurants',
       'Food & Drink - Vending machines', 'General Merchandise - Books',
       'General Merchandise - Clothing',
       'General Merchandise - Electronics',
       'General Merchandise - Houseware',
       'General Merchandise - Online Marketplaces',
       'General Merchandise - Pet supplies',
       'General Merchandise - Product refunds',
       'General Merchandise - Sporting goods',
       'General Services - Auto insurance',
       'General Services - Cloud storage', 'General Services - Education',
       'General Services - Health + Fitness',
       'General Services - Health insurance',
       'General Services - Home Repair + Maintenance',
       'General Services - Other insurance',
       'General Services - Other non-entertainment',
       'General Services - Other non-entertainment online subscriptions',
       'General Services - Service refunds',
       'General Services - Shipping + Postage',
       'Government + Non-Profit - Other',
       'Government + Non-Profit - Other donations',
       'Government + Non-Profit - Political donations',
       'Government + Non-Profit - Taxes', 'Income - Other',
       'Income - Salary', 'Income - Tax refund',
       'Loans - Car loan payments', 'Loans - Credit card payment',
       'Loans - Mortgage Payments', 'Loans - Mortgage payments',
       'Loans - Personal loans', 'Medical - Pharmacies and supplements',
       'Medical - Veterin ary services', 'Medical - Veterinary services',
       'Rent & Utilities - Internet', 'Rent & Utilities - Mobile Phone',
       'Rent & Utilities - Rent', 'Rent & Utilities - Water',
       'Subscription - Others', 'Supermarkets - Groceries',
       'Transportation - Automobile maintenance and fees',
       'Transportation - Gas', 'Transportation - Parking',
       'Transportation - Public Transport',
       'Transportation - Taxis and rideshares', 'Transportation - Tolls',
       'Travel - Flights', 'Travel - Lodging', 'Travel - Rental cars'],
      dtype='<U63')

In [ ]:
pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting transformers<5.0.0,>=4.6.0 (from sentence_transformers)
  Downloading transformers-4.31.0-py3-none-any.whl (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 13.1 MB/s eta 0:00:00
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.65.0)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (2.0.1+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.15.2+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.22.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.10.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (3.8.1)
Collecting sentencepiece (from sentence_transformers)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.3 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0 (from sentence_transformers)
  Downloading huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (3.12.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2.27.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (4.7.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (23.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->sentence_transformers) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->sentence_transformers) (16.0.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2022.10.31)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers<5.0.0,>=4.6.0->sentence_transformers)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 36.2 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers<5.0.0,>=4.6.0->sentence_transformers)
  Downloading safetensors-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.6 MB/s eta 0:00:00
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (8.1.6)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence_transformers) (8.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence_transformers) (2.1.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.4)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence_transformers) (1.3.0)
Building wheels for collected packages: sentence_transformers
  Building wheel for sentence_transformers (setup.py) ... done
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=518c3afc5b4c73ea2747374403ca5db71f4942acc37b86eb751bd2edd88a7eb9
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers
Installing collected packages: tokenizers, sentencepiece, safetensors, huggingface-hub, transformers, sentence_transformers
Successfully installed huggingface-hub-0.16.4 safetensors-0.3.1 sentence_transformers-2.2.2 sentencepiece-0.1.99 tokenizers-0.13.3 transformers-4.31.0

In [ ]:
from sentence_transformers import SentenceTransformer
#sentences = ["This is an example sentence", "Each sentence is converted"]
modeld = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

Downloading (…)a8e1d/.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading (…)_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading (…)b20bca8e1d/README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading (…)0bca8e1d/config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading (…)ce_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading (…)e1d/data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading (…)nce_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading (…)a8e1d/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading (…)8e1d/train_script.py:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading (…)b20bca8e1d/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)bca8e1d/modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [ ]:
import pickle
with open('embedding_pickle','wb') as f:
 pickle.dump(modeld,f)

In [ ]:
description=datagpt['Transaction Description'].tolist()
embeddings = modeld.encode(description)

In [ ]:
embeddings

array([[ 0.01363903,  0.02460667, -0.01300609, ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.01149002,  0.04829252, -0.00755107, ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [-0.04387978, -0.05286455, -0.00526158, ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.03993556,  0.01457984, -0.0148067 , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.04097003, -0.07378092, -0.02182727, ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.04415144,  0.04374549,  0.0096705 , ..., -0.02912224,
        -0.03370368,  0.00446712]], dtype=float32)

In [ ]:
import numpy as np
features=np.concatenate((one_hot_array,scaled_transaction_amount,embeddings),axis = 1)
features

array([[ 0.        ,  0.        ,  0.        , ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.        ,  0.        ,  0.        , ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [ 0.        ,  0.        ,  0.        , ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.        ,  0.        ,  0.        , ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.        ,  0.        ,  0.        , ..., -0.02912224,
        -0.03370368,  0.00446712]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,encoded_labels , test_size=0.2, random_state=42 ,stratify=encoded_labels)

In [ ]:
import xgboost as xgb

In [ ]:
# Convert the dataset into DMatrix format (optimized for XGBoost)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [ ]:
# Define XGBoost parameters
params = {
'objective': 'multi:softmax', # Multi-class classification
'num_class': len(datagpt['Transaction Category'].unique()), # Number of classes
'eval_metric': 'merror', # Error rate metric
'max_depth': 5, # Maximum depth of a tree
'min_child_weight': 1, # Minimum sum of instance weight needed in a child
'subsample': 0.8, # Subsample ratio of the training instances
'colsample_bytree': 0.8, # Subsample ratio of columns when constructing each tree
'gamma': 0.1, # Minimum loss reduction required to make a further partition on a leaf node
'reg_alpha': 0.1, # L1 regularization term on weights
'reg_lambda': 0.1, # L2 regularization term on weights
'seed': 42 # Random seed for reproducibility
}

In [ ]:
# Train the XGBoost model
num_rounds = 100 # Number of boosting rounds
updated_model = xgb.train(params, dtrain, num_rounds,xgb_model=model)

In [ ]:
# Make predictions on the test set
y_pred = updated_model.predict(dtest)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, zero_division = 0)
print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(confusion_mat)
print("\nClassification Report:")
print(classification_rep)

Accuracy: 0.9346

Confusion Matrix:
[[ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 10 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 13]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.50      1.00      0.67         1
         1.0       0.00      0.00      0.00         1
         2.0       1.00      1.00      1.00        10
         3.0       0.90      1.00      0.95         9
         4.0       0.00      0.00      0.00         1
         5.0       0.89      1.00      0.94        16
         6.0       1.00      1.00      1.00        13
         7.0       0.90      1.00      0.95         9
         8.0       1.00      1.00      1.00         9
         9.0       0.00      0.00      0.00         1
        10.0       1.00      1.00      1.00        13
        11.0       1.00      1.00      1.00         1
        12.0       0.89      1.00      0.94         8
        13.0       1.00      0.83      0.91         6
        14.0       1.00      0.50      0.67         2
        15.0       1.00      0.50      0.67         2
        16.0       0.92      1.00      0.96        12
        17.0       1.00      1.00      1.00         4
        18.0       0.67      1.00      0.80         2
        19.0       1.00      0.75      0.86         4
        20.0       1.00      0.75      0.86         4
        21.0       0.67      0.50      0.57         4
        22.0       0.50      1.00      0.67         1
        23.0       0.00      0.00      0.00         1
        24.0       1.00      0.50      0.67         2
        25.0       1.00      1.00      1.00        12
        26.0       0.91      1.00      0.95        10
        27.0       0.92      1.00      0.96        11
        28.0       1.00      1.00      1.00         9
        29.0       0.88      1.00      0.93        14
        30.0       1.00      1.00      1.00         4
        31.0       0.86      1.00      0.92         6
        32.0       1.00      1.00      1.00         2
        33.0       0.86      1.00      0.92         6
        34.0       0.89      1.00      0.94         8
        35.0       1.00      1.00      1.00         6
        36.0       1.00      1.00      1.00         6
        37.0       1.00      1.00      1.00         9
        38.0       1.00      1.00      1.00         6
        39.0       1.00      1.00      1.00         6
        40.0       1.00      1.00      1.00         6
        41.0       1.00      1.00      1.00         6
        42.0       1.00      0.73      0.84        11
        43.0       0.92      1.00      0.96        11
        44.0       1.00      1.00      1.00        10
        45.0       0.50      0.75      0.60         4
        46.0       1.00      1.00      1.00         8
        47.0       1.00      1.00      1.00        10
        48.0       1.00      0.50      0.67         4
        49.0       0.75      0.60      0.67         5
        50.0       0.50      0.50      0.50         2
        51.0       0.00      0.00      0.00         0
        52.0       1.00      1.00      1.00         2
        53.0       1.00      1.00      1.00         9
        54.0       1.00      1.00      1.00        10
        55.0       1.00      1.00      1.00        10
        56.0       1.00      1.00      1.00        10
        57.0       1.00      1.00      1.00         2
        58.0       1.00      1.00      1.00         7
        59.0       1.00      0.75      0.86         8
        60.0       1.00      1.00      1.00         3
        61.0       0.67      1.00      0.80         2
        62.0       1.00      1.00      1.00         1
        63.0       0.90      0.82      0.86        11
        64.0       1.00      0.88      0.93         8
        65.0       1.00      0.67      0.80         3
        66.0       0.00      0.00      0.00         1
        67.0       1.00      1.00      1.00        13

    accuracy                           0.93       428
   macro avg       0.84      0.83      0.83       428
weighted avg       0.94      0.93      0.93       428

In [ ]:
from sklearn.preprocessing import OneHotEncoder
def encode_Ids(column_vector, categories):
# Create an instance of the OneHotEncoder
    encoder = OneHotEncoder(categories=[categories], sparse=False)
# Reshape the column vector to a 2D array
    column_vector = column_vector.reshape(-1, 1)
# Perform one-hot encoding on the column vector
    encoded_vector = encoder.fit_transform(column_vector)
    return encoded_vector

In [ ]:
def new_classification(matrix):
    IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
# Perform one-hot encoding on the first column
    encoded_column1 = encode_Ids(matrix[:,0],IDs)
    column2 = (matrix[:, 1].astype(float) - 4)/(6400 - 4)

    column3 = modeld.encode(matrix[:, 2])
# Combine the columns to form the updated matrix
    updated_matrix = np.concatenate((encoded_column1, column2.reshape(-1,1), column3), axis = 1)
# Convert the new data into DMatrix format
    dnew = xgb.DMatrix(updated_matrix)
# Make predictions on the new data
    predictions = updated_model.predict(dnew)
# Inverse transform the encoded predictions to get the original category names
    predicted_categories = label_encoder.inverse_transform(predictions.astype(int))
# Print the predicted categories
    for category in predicted_categories:
        print(f"Predicted Category: {category}")
    return(predictions)

In [ ]:
newclass=np.array([['SEW0C_LI.1','60','Trendy threads - Smoking'],
                   ['SEWC_PA.1','25','IKEA - defective product refund'],
                   ['SEWC_P.1','90','Puma - Football jersey'],
                   ['SEWC_P_PL.1','340','Khan Academy - Math learning path'],
                   ['HP.1','320','Premium package health insurance - UnitedHealthcare'],
                   ['TA.1','55','Poker cards bet'],
                   ['HP.1','180','Sex on the beach bottle'],
                   ['CPA_MP.1','60','Penalty of insufficient funds']])
new_classification(newclass)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Predicted Category: Income - Tax refund
Predicted Category: Income - Tax refund
Predicted Category: General Merchandise - Sporting goods
Predicted Category: General Services - Education
Predicted Category: General Services - Health insurance
Predicted Category: Food & Drink - Coffee and tea
Predicted Category: Food & Drink - Fast food
Predicted Category: Bank Transfers - Overdraft fees

array([44., 44., 26., 29., 31., 13., 14.,  5.], dtype=float32)

In [ ]:
with open('retrained_transaction_pickle','wb') as f:
 pickle.dump(updated_model,f)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
encoder=OneHotEncoder(categories=[IDs], sparse=False)

In [ ]:
encoder.fit_transform([['CPA.1']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import pickle
with open('encoder_pickle','wb') as f:
 pickle.dump(encoder,f)